version: "1.1"
services:
  app:
    build:
      context: .
      dockerfile: 2023-6315-1/dockerfile
    links:
      - db
    ports:
      - "5000:5000"

  db:
      image: mysql
      ports:
        - "3308:3306"
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: SSME6315-020302D
        MYSQL_DATABASE: motorcycleshop
        MYSQL_HOST: 127.0.0.1
      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro