version: "3"
services:
  app:
    build:
      context: .
      dockerfile: /Users/edavkinstepan/2023-6315-1/dockerfile
    links:
      - db
    ports:
      - "5000:5000"
  web:
    build:
      context: .
      dockerfile: /Users/edavkinstepan/2023-6315-1/Dockerfile.frontend
    ports:
      - "8080:80"
  db:
      image: mysql:8.0.33
      ports:
        - "30000:3306"
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: SSME6315-020302D
      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro